//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGameDemo.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyGame")]
    public interface IMyGame {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyGame/GetAnswer", ReplyAction="http://tempuri.org/IMyGame/GetAnswerResponse")]
        string GetAnswer(string question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyGame/GetAnswer", ReplyAction="http://tempuri.org/IMyGame/GetAnswerResponse")]
        System.Threading.Tasks.Task<string> GetAnswerAsync(string question);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyGameChannel : MyGameDemo.ServiceReference1.IMyGame, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyGameClient : System.ServiceModel.ClientBase<MyGameDemo.ServiceReference1.IMyGame>, MyGameDemo.ServiceReference1.IMyGame {
        
        public MyGameClient() {
        }
        
        public MyGameClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyGameClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyGameClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyGameClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAnswer(string question) {
            return base.Channel.GetAnswer(question);
        }
        
        public System.Threading.Tasks.Task<string> GetAnswerAsync(string question) {
            return base.Channel.GetAnswerAsync(question);
        }
    }
}
